### ISSUE TITLE
Issue with text color in d3 :sob:

### ISSUE THREAD

**Issue by annalexc** [annalexc/space-rocks#2]
``` js
var label = asteroidField.append("text")
      .attr("class", "label")
      .attr("text-anchor", "end")
      .attr("y", h - 24)
      .attr("x", w)
      .style("color", "white")
      .text(2016)
```

😭

**Comment by DZGoldman** [comment]
is this helpful and/or relevant?
http://stackoverflow.com/questions/22523204/how-to-set-text-color-for-my-d3-chart-title

**Comment by ajhofferber** [comment]
yeah! If you're working with D3, chances are that text is actually SVG. so you'd need to change the fill style for the path instead of treating it like regular text.

**Comment by CentroDL** [comment]
you could instead give a class and style that class instead of trying to inline style it

**Comment by annalexc** [comment]
`fill` works!! LOVE YOU ALL, thanks.
![otter](https://66.media.tumblr.com/f0b8e23885e75b92e8594a8d490330ac/tumblr_o12acmIifv1us72huo1_r1_400.gif)
